/* Generated By:JavaCC: Do not edit this line. DotParserConstants.java */
package org.wilmascope.dotparser;

public interface DotParserConstants {

	int EOF = 0;
	int SINGLE_LINE_COMMENT = 6;
	int FORMAL_COMMENT = 7;
	int MULTI_LINE_COMMENT = 8;
	int GRAPH = 9;
	int DIGRAPH = 10;
	int NODE = 11;
	int LABEL = 12;
	int POS = 13;
	int RATIO = 14;
	int SHAPE = 15;
	int BB = 16;
	int WIDTH = 17;
	int WEIGHT = 18;
	int HEIGHT = 19;
	int CONCENTRATE = 20;
	int LAYER = 21;
	int LAYERS = 22;
	int MINLEN = 23;
	int ID = 24;
	int CTLSTRING = 25;
	int NUM = 26;
	int DEC = 27;
	int IGNOREPARAMETERS = 30;

	int DEFAULT = 0;
	int NODEPARAMETERS = 1;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\\\\"", "<SINGLE_LINE_COMMENT>",
			"<FORMAL_COMMENT>", "<MULTI_LINE_COMMENT>", "\"graph\"", "\"digraph\"", "\"node\"", "\"label\"", "\"pos\"",
			"\"ratio\"", "\"shape\"", "\"bb\"", "\"width\"", "\"weight\"", "\"height\"", "\"concentrate\"",
			"\"layer\"", "\"layers\"", "\"minlen\"", "<ID>", "<CTLSTRING>", "<NUM>", "<DEC>", "\" \"", "\"\\t\"",
			"<IGNOREPARAMETERS>", "\"{\"", "\"}\"", "\";\"", "\"[\"", "\"=\"", "\",\"", "\"]\"", "\"->\"", };

}
