/* Generated By:JavaCC: Do not edit this line. AugmentedGMLParserConstants.java */
package org.wilmascope.gmlparser;

public interface AugmentedGMLParserConstants {

	int EOF = 0;
	int GRAPH = 17;
	int VERSION = 18;
	int DIRECTED = 19;
	int NAME = 20;
	int NODE = 21;
	int EDGE = 22;
	int ID = 23;
	int LABEL = 24;
	int SOURCE = 25;
	int TARGET = 26;
	int SERIES = 27;
	int ITEM = 28;
	int VALUE = 29;
	int NUM = 30;
	int DEC = 31;
	int CTLSTRING = 32;

	int DEFAULT = 0;
	int IN_IGNORABLE = 1;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\\\\"", "\"Line\"",
			"\"LabelGraphics\"", "\"Graphics\"", "\"graphics\"", "\"node_style\"", "\"edge_style\"", "\"style\"",
			"\"edgeAnchor\"", "\"[\"", "\"]\"", "<token of kind 16>", "\"graph\"", "\"version\"", "\"directed\"",
			"\"name\"", "\"node\"", "\"edge\"", "\"id\"", "\"label\"", "\"source\"", "\"target\"", "\"series\"",
			"\"item\"", "\"value\"", "<NUM>", "<DEC>", "<CTLSTRING>", "\"[\"", "\"]\"", };

}
